#pragma once

#define RESPIRA_PRINCIPAL 0
#define ABAIXADO_PRINCIPAL 1
#define CORRENDO_PRINCIPAL 2
#define PULO1_PRINCIPAL 3
#define PULO2_PRINCIPAL 4
#define CAIR_PRINCIPAL 5
#define PULAMURO_PRINCIPAL 7
#define ATAQUE1_PRINCIPAL 8
#define ATAQUE2_PRINCIPAL 10
#define ATAQUE3_PRINCIPAL 11
#define DESLIZA_PRINCIPAL 9
#define APANHA_PRINCIPAL 12

#define PARADO_GOBLIN 0
#define TACA_BOMBAGOBLIN 1
#define CORRENDO_GOBLIN 2
#define GOBLIN_BATENDO 3
#define APANHA_GOBLIN 4
#define MORRE_GOBLIN 5