#pragma once

#define RESPIRA_PRINCIPAL 0
#define ABAIXADO_PRINCIPAL 1
#define CORRENDO_PRINCIPAL 2
#define PULO1_PRINCIPAL 3
#define PULO2_PRINCIPAL 4
#define CAIR_PRINCIPAL 5
#define DESLIZAR_PRINCIPAL 6
#define PULAMURO_PRINCIPAL 7
#define ATAQUE1_PRINCIPAL 8
#define PARADO_GOBLIN 0
#define TACA_BOMBAGOBLIN 1
#define CORRENDO_GOBLIN 2
#define GOBLIN_BATENDO 3