#pragma once

#define RESPIRA_PRINCIPAL 0
#define ABAIXADO_PRINCIPAL 1
#define CORRENDO_PRINCIPAL 2
#define PULO1_PRINCIPAL 3
#define PULO2_PRINCIPAL 4
#define CAIR_PRINCIPAL 5
#define PULAMURO_PRINCIPAL 7
#define ATAQUE1_PRINCIPAL 8
#define ATAQUE2_PRINCIPAL 10
#define ATAQUE3_PRINCIPAL 11
#define DESLIZA_PRINCIPAL 9
#define APANHA_PRINCIPAL 12

#define PARADO 0
#define ATAQUE1 1
#define CORRENDO 2
#define ATAQUE2 3
#define APANHA 4
#define MORRE 5
#define VOA 6